config/routes.rb
Rails.application.routes.draw do
  resources :geos

  root 'users#home'

  resources :users, except: [:index, :show]
  resource :session, only: [:new, :create, :destroy]
  get 'users/main' => 'users#main'
  get 'users/cities' => 'users#cities'

  get '/users/miami' => "users#miami"
  get '/users/ny' => "users#ny"
  get '/users/newyork' => "users#newyork"
  get '/users/la' => "users#la"
  get '/users/losangeles' => "users#losangeles"

  get 'users/checkout' => "users#checkout"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/geo.rb
class Geo < ActiveRecord::Base
	geocoded_by :full_street_address   # can also be an IP address
	after_validation :geocode          # auto-fetch coordinates
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :email, :email => {:strict_mode => true}
	phony_normalize :phone_number, :default_country_code => 'US'
	validates :phone_number, :phony_plausible => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
  	return nil unless session[:session_token]
  	@current_user ||= User.find_by(session_token: session[:session_token])
  end

  private

  def login!(user)
  	session[:session_token] = make_token
  	user.session_token = session[:session_token]
  	user.save!
  end

  def logout!
  	current_user.update(session_token: nil)
  	session[:session_token] = make_token
  end

  def make_token
  	return SecureRandom.urlsafe_base64
  end

  def require_current_user
  	redirect_to new_session_url unless current_user
  end
end

app/controllers/geos_controller.rb
class GeosController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :require_current_user, only: [:destroy, :main]

	def new
		@user = User.new
	end

	def create
		@user = User.find_by(email: session_params[:email])
		if @user && @user.authenticate(session_params[:password])
			login!(@user)
			redirect_to "/users/main"
		else
			flash[:notice] = "Incorrect email or password"
			redirect_to root_path
		end
	end

	def destroy
		logout!
		redirect_to new_session_url
	end
	
	private

	def session_params
		@session_params ||= params.require(:session).permit(:email, :first_name, :last_name, :phone_number, :password)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :user_is_current_user, only: [:edit, :update]

	def current
		respond_to do |format|
			format.json {
				render json: {
					id: current_user.id,
					email: current_user.email,
					first_name: current_user.first_name,
					last_name: current_user.last_name,
					phone_number: current_user.phone_number
				}
			}
		end
	end

	def home
		@user = User.new
	end

	def main
		# @employees = Employee.all
		@my_time = Time.now
	end
	def la
	end

	def ny

	end
	def cities
		binding.pry
	end

	def miami
		@employees = Employee.all.where("city='Miami'")
		respond_to do |format|
			format.html { render text: "Please go to emplyees.json" }
			format.json { render json: @employees.to_json }
		end
	end

	def newyork
		@employees = Employee.all.where("city='New York'")
		respond_to do |format|
			format.html { render text: "Please go to emplyees.json" }
			format.json { render json: @employees.to_json }
		end
	end

	def losangeles
		@employees = Employee.all.where("city='Los Angeles'")
		respond_to do |format|
			format.html { render text: "Please go to emplyees.json" }
			format.json { render json: @employees.to_json }
		end
	end

	def employees
		@employees = Employee.all
		respond_to do |format|
			format.html { render text: "Please go to emplyees.json" }
			format.json { render json: @employees.to_json }
		end
	end
	def list
		@employees = Employee.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new( user_params )
		if @user.save
			redirect_to users_main_url
		else
			# binding.pry
			render :new, notice: "#{@user.email} is not a valid email"
		end
	end

	def edit
		@user = current_user
	end

	def update
		@user = current_user

		if @user.authenticate(params[:user][:current_password])
			@user.update(password_params)
			# redirect_to
		else
			render :edit
		end
	end

	def checkout


	end

	private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :phone_number)
	end

	def password_params
		params.require(:user).permit(:password, :password_confirmation)
	end

	def user_is_current_user
		user = User.find(params[:id])

		if user
			# redirect_to
		else
			# redirect_to new_session_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/geos_helper.rb
module GeosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Hiker</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Carrois+Gothic+SC' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="http://fontawesome.io/assets/font-awesome/css/font-awesome.css">
	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
</head>
<body>


	<%= yield %>

</body>
</html>

app/views/users/checkout.html.erb
<div class="container">
  <form class="form-horizontal" role="form">
    <fieldset>
      <legend>Payment</legend>
      <div class="form-group">
        <label class="col-sm-3 control-label" for="card-holder-name">Name on Card</label>
        <div class="col-sm-9">
          <input type="text" class="form-control" name="card-holder-name" id="card-holder-name" placeholder="Card Holder's Name">
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label" for="card-number">Card Number</label>
        <div class="col-sm-9">
          <input type="text" class="form-control" name="card-number" id="card-number" placeholder="Debit/Credit Card Number">
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label" for="expiry-month">Expiration Date</label>
        <div class="col-sm-9">
          <div class="row">
            <div class="col-xs-3">
              <select class="form-control col-sm-2" name="expiry-month" id="expiry-month">
                <option>Month</option>
                <option value="01">Jan (01)</option>
                <option value="02">Feb (02)</option>
                <option value="03">Mar (03)</option>
                <option value="04">Apr (04)</option>
                <option value="05">May (05)</option>
                <option value="06">June (06)</option>
                <option value="07">July (07)</option>
                <option value="08">Aug (08)</option>
                <option value="09">Sep (09)</option>
                <option value="10">Oct (10)</option>
                <option value="11">Nov (11)</option>
                <option value="12">Dec (12)</option>
              </select>
            </div>
            <div class="col-xs-3">
              <select class="form-control" name="expiry-year">
                <option value="13">2013</option>
                <option value="14">2014</option>
                <option value="15">2015</option>
                <option value="16">2016</option>
                <option value="17">2017</option>
                <option value="18">2018</option>
                <option value="19">2019</option>
                <option value="20">2020</option>
                <option value="21">2021</option>
                <option value="22">2022</option>
                <option value="23">2023</option>
              </select>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label" for="cvv">Card CVV</label>
        <div class="col-sm-3">
          <input type="text" class="form-control" name="cvv" id="cvv" placeholder="Security Code">
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
          <button type="button" class="btn btn-success">Pay Now</button>
        </div>
      </div>
    </fieldset>
  </form>
</div>

app/views/users/home.html.erb
<body class="home">
	<nav class="main-nav" id="main-nav">
		<a class="cities" value="miami" href="users/main">Miami</a>
		<a class="cities" value="la" href="users/la">Los Angeles</a>
		<a class="cities" value="ny" href="users/ny">New York</a>
		<a href="users/aboutus">About Us</a>
	</nav>

	<div class="page-wrap">

		<header class="main-header">
			<a href="#main-nav" class="open-menu">
				☰
			</a>
			<a href="#" class="close-menu">
				☰
			</a>

			<h1 class="wash">WASH<div class="right">Sign In/Register</div></h1>
			
		</header>

		<div class="content">
			<h1>A Whole New <br> Car Washing Experience</h1>
			<%= form_for @user, as: :session, url: session_url, html: { class: "loginform"} do |f| %>
			<div class="form-group">
				<label for="email">Email address</label>
				<input type="email" name="session[email]" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
			</div>
			<div class="form-group">
				<label for="exampleInputPassword1">Password</label>
				<input type="password" name="session[password]" class="form-control" id="exampleInputPassword1" placeholder="Password">
			</div>
			<%= f.submit "Log in", class: "submit" %>
			<% end %>

			<% if flash[:notice] %>
			<div class="notice"><%= flash[:notice] %></div>
			<% end %>
			
		</div>

	</div>
</div>

</body>

app/views/users/la.html.erb
<div class="cityform">
<%= form_tag "/users/la", method: "get", class: "la" do |t| %>
Enter your address:
<input type="text" name="address">
<%= submit_tag "Search" %>
<!-- Select a Time:
<%= select_hour(@my_time, start_hour: 1, end_hour: 12) %>
<select name="minutes">
	<option value="0">00</option>
	<option value="15">15</option>
	<option value="30">30</option>
	<option value="45">45</option>
</select>
<select name="ampm">
	<option value="am">AM</option>
	<option value="pm">PM</option>
</select> -->

<% end %>
</div>

<div id="map-canvas">
</div>

app/views/users/main.html.erb
<div class="cityform">
<%= form_tag "/users/main", method: "get" do |t| %>
Enter your address:
<input type="text" name="address">
<%= submit_tag "Search" %>
<!-- Select a Time:
<%= select_hour(@my_time, start_hour: 1, end_hour: 12) %>
<select name="minutes">
	<option value="0">00</option>
	<option value="15">15</option>
	<option value="30">30</option>
	<option value="45">45</option>
</select>
<select name="ampm">
	<option value="am">AM</option>
	<option value="pm">PM</option>
</select> -->

<% end %>
</div>

<div id="map-canvas">
</div>

app/views/users/new.html.erb
<body class="signup">
  <main class="gateway">
    <h1>Sign up</h1>

    <%= form_for @user do |f| %>
    Email:
    <%= f.text_field :email, placeholder: "email" %>
    <br/>
    Password:
    <%= f.password_field :password, placeholder: "password" %>
    <br/>
    Confirm Password:
    <%= f.password_field :password_confirmation, placeholder: "confirm password"%>
    <br/>
    First Name:
    <%= f.text_field :first_name, placeholder: "First Name" %>
    <br/>
    Last Name:
    <%= f.text_field :last_name, placeholder: "Last Name" %>
    <br/>
    Phone Number:
    <%= f.telephone_field(:phone_number)%>
    <br/>
    <!-- <p><%= notice %></p> -->
    <center><%= f.submit "Sign up" , :class => "buttonnew"%></center>

    <% end %>
  </main>
</body>

app/views/users/ny.html.erb
<div class="cityform">
<%= form_tag "/users/ny", method: "get", class: "ny" do |t| %>
Enter your address:
<input type="text" name="address">
<%= submit_tag "Search" %>
<!-- Select a Time:
<%= select_hour(@my_time, start_hour: 1, end_hour: 12) %>
<select name="minutes">
	<option value="0">00</option>
	<option value="15">15</option>
	<option value="30">30</option>
	<option value="45">45</option>
</select>
<select name="ampm">
	<option value="am">AM</option>
	<option value="pm">PM</option>
</select> -->

<% end %>
</div>

<div id="map-canvas">
</div>